import { REQUIREMENT as R } from './requirements.mjs'

/* ============================================================
   Skill catalogue
   ---------------
   What PixGPT can do, described once, in terms of the systems that
   actually implement it.

   Every skill names the tools it needs from the existing tool registry
   and the requirements that must resolve before it is offered. Nothing
   here implements a capability — a skill is a declaration that binds
   an intent to machinery that already exists.

   `permission` is the ceiling, not a grant. A skill listing an
   approval-gated tool does not thereby gain approval; the command
   classifier still decides at execution time. A skill can never widen
   its own permissions.
   ============================================================ */

export const CATEGORY = Object.freeze({
  AI: 'ai',
  CODING: 'coding',
  UI_UX: 'ui_ux',
  DESIGN: 'design',
  RESEARCH: 'research',
  BROWSER: 'browser',
  FILES: 'files',
  DOCUMENTS: 'documents',
  DATA: 'data',
  IMAGE: 'image',
  VIDEO: 'video',
  AUDIO: 'audio',
  DEVOPS: 'devops',
  SECURITY: 'security',
  PRODUCTIVITY: 'productivity',
  AUTOMATION: 'automation',
  CUSTOM: 'custom',
})

export const CATEGORY_LABELS = Object.freeze({
  ai: 'AI',
  coding: 'Coding',
  ui_ux: 'UI / UX',
  design: 'Design',
  research: 'Research',
  browser: 'Browser',
  files: 'Files',
  documents: 'Documents',
  data: 'Data',
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
  devops: 'DevOps',
  security: 'Security',
  productivity: 'Productivity',
  automation: 'Automation',
  custom: 'Custom',
})

export const STATUS = Object.freeze({
  AVAILABLE: 'available',
  ENABLED: 'enabled',
  DISABLED: 'disabled',
  REQUIRES_CONFIG: 'requires_config',
  UNSUPPORTED: 'unsupported',
  COMING_SOON: 'coming_soon',
  ERROR: 'error',
})

export const PERMISSION = Object.freeze({
  SAFE: 'safe',
  APPROVAL_REQUIRED: 'approval_required',
  RESTRICTED: 'restricted',
})

/**
 * A skill:
 *   id, name, description, category, icon
 *   requires[]   requirement ids that must resolve
 *   tools[]      tool-registry names it needs
 *   permission   the ceiling for what it may do
 *   match[]      patterns that suggest it for a request
 *   settings{}   user-adjustable configuration
 *   mode         which product mode it belongs to
 */
const S = (skill) => ({
  requires: [],
  tools: [],
  permission: PERMISSION.SAFE,
  match: [],
  settings: null,
  ...skill,
})

export const BUILT_IN = [
  /* ---------- AI ---------- */
  S({
    id: 'vision',
    name: 'Vision',
    description: 'Read and reason about images you attach, and inspect screenshots during QA.',
    category: CATEGORY.AI,
    icon: 'Eye',
    requires: [R.MODEL_VISION],
    /*
     * Vision READS an image; it does not make one. A bare /image/ match pulled
     * it into every "generate an image" request, which is the opposite
     * capability and left the user thinking generation was available.
     */
    match: [
      /\b(look at|see|read|describe|analyse|analyze|inspect|check)\b.{0,24}\b(image|screenshot|photo|picture|diagram)\b/i,
      /\bwhat(\s+does|'?s)\b.{0,24}\b(image|screenshot|photo|picture)\b/i,
      /\b(this|that|the|attached|uploaded)\s+(image|screenshot|photo|picture|diagram)\b/i,
    ],
    notWhen: [/\b(generate|create|make|draw|render|produce)\b.{0,20}\b(image|picture|photo|graphic)\b/i],
  }),
  S({
    id: 'summarization',
    name: 'Summarization',
    description: 'Condense long text, documents or conversations into what matters.',
    category: CATEGORY.AI,
    icon: 'AlignLeft',
    requires: [R.GATEWAY],
    match: [/\bsummar/i, /\btl;?dr\b/i, /\bkey points\b/i, /\bcondense\b/i],
  }),
  S({
    id: 'translation',
    name: 'Translation',
    description: 'Translate between languages, preserving tone and formatting.',
    category: CATEGORY.AI,
    icon: 'Languages',
    requires: [R.GATEWAY],
    match: [/\btranslate\b/i, /\bin (spanish|french|german|japanese|chinese|hindi|tamil|arabic)\b/i],
  }),
  S({
    id: 'reasoning',
    name: 'Reasoning',
    description: 'Work through multi-step problems methodically rather than answering off the cuff.',
    category: CATEGORY.AI,
    icon: 'Brain',
    requires: [R.GATEWAY],
    match: [/\bwhy\b.*\?/i, /\bexplain how\b/i, /\bwork (it |this )?out\b/i, /\bstep by step\b/i],
  }),
  S({
    id: 'structured-output',
    name: 'Structured Output',
    description: 'Return JSON, tables or a fixed schema instead of prose.',
    category: CATEGORY.AI,
    icon: 'Braces',
    requires: [R.GATEWAY],
    match: [/\bas json\b/i, /\bstructured\b/i, /\bschema\b/i, /\bas a table\b/i],
  }),
  S({
    id: 'tool-calling',
    name: 'Tool Calling',
    description: 'Let the model call server-side tools to act rather than only describe.',
    category: CATEGORY.AI,
    icon: 'Wrench',
    requires: [R.MODEL_TOOLS],
  }),
  S({
    id: 'long-context',
    name: 'Long Context',
    description: 'Keep large documents and long conversations coherent within the context budget.',
    category: CATEGORY.AI,
    icon: 'ScrollText',
    requires: [R.GATEWAY],
  }),
  S({
    id: 'model-comparison',
    name: 'Model Comparison',
    description: 'See which model answered, when a fallback was used, and why.',
    category: CATEGORY.AI,
    icon: 'GitCompare',
    requires: [R.GATEWAY],
    match: [/\bwhich model\b/i, /\bcompare models\b/i],
  }),
  S({
    id: 'document-understanding',
    name: 'Document Understanding',
    description: 'Answer questions about an attached PDF, Word file, spreadsheet or code file.',
    category: CATEGORY.AI,
    icon: 'FileSearch',
    requires: [R.DOCUMENTS],
    match: [/\bthis (document|pdf|file)\b/i, /\battached\b/i, /\baccording to the\b/i],
  }),
  S({
    id: 'context-optimization',
    name: 'Context Optimization',
    description: 'Trim and prioritise what is sent to the model so long tasks stay coherent.',
    category: CATEGORY.AI,
    icon: 'Minimize2',
    requires: [R.GATEWAY],
  }),

  /* ---------- Coding ---------- */
  S({
    id: 'project-planning',
    name: 'Project Planning',
    description: 'Break a build into ordered steps and track them as a checklist.',
    category: CATEGORY.CODING,
    icon: 'ListChecks',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['report_plan'],
    mode: 'build',
    match: [/\bplan\b/i, /\bbreak (this |it )?down\b/i, /\broadmap\b/i],
  }),
  S({
    id: 'codebase-analysis',
    name: 'Codebase Analysis',
    description: 'Map an unfamiliar project: stack, entry points, routes, tests and commands.',
    category: CATEGORY.CODING,
    icon: 'FolderTree',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['analyze_project', 'list_files', 'read_file', 'search_code'],
    mode: 'build',
    match: [/\banalyse|analyze\b.*\b(code|project|repo)/i, /\bunderstand (this|the) (code|project)/i, /\bwhat does this (do|project)/i],
  }),
  S({
    id: 'architecture',
    name: 'Architecture',
    description: 'Design module boundaries, data flow and where responsibilities belong.',
    category: CATEGORY.CODING,
    icon: 'Network',
    requires: [R.MODEL_TOOLS],
    mode: 'build',
    match: [/\barchitect/i, /\bdesign the (system|structure)/i, /\bhow should I structure\b/i],
  }),
  S({
    id: 'feature-development',
    name: 'Feature Development',
    description: 'Implement a feature end to end, then run it and check that it works.',
    category: CATEGORY.CODING,
    icon: 'Hammer',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'edit_file', 'run_command', 'read_file'],
    mode: 'build',
    match: [/\b(build|create|make|add|implement)\b.*\b(app|site|page|feature|component|api|endpoint)/i],
  }),
  S({
    id: 'bug-fixing',
    name: 'Bug Fixing',
    description: 'Reproduce a fault, find the root cause, fix it, and prove the fix.',
    category: CATEGORY.CODING,
    icon: 'Bug',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['read_file', 'edit_file', 'run_command', 'search_code'],
    mode: 'debug',
    match: [/\bfix\b/i, /\bbug\b/i, /\bbroken\b/i, /\bnot working\b/i, /\berror\b/i, /\bfails?\b/i],
  }),
  S({
    id: 'debugging',
    name: 'Debugging',
    description: 'Trace a failure through logs, the console and the network rather than guessing.',
    category: CATEGORY.CODING,
    icon: 'SearchCode',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command', 'browser_diagnostics', 'search_code'],
    mode: 'debug',
    match: [/\bdebug\b/i, /\bwhy (is|does).*\b(fail|break|crash)/i, /\bstack trace\b/i],
  }),
  S({
    id: 'refactoring',
    name: 'Refactoring',
    description: 'Restructure code without changing behaviour, with tests to prove it.',
    category: CATEGORY.CODING,
    icon: 'Replace',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['read_file', 'edit_file', 'run_command'],
    mode: 'build',
    match: [/\brefactor/i, /\bclean up\b.*\bcode/i, /\btidy\b/i, /\bsimplify\b/i],
  }),
  S({
    id: 'code-review',
    name: 'Code Review',
    description: 'Read a change for correctness, clarity and risk, and say what actually matters.',
    category: CATEGORY.CODING,
    icon: 'ScanEye',
    requires: [R.MODEL_TOOLS],
    tools: ['read_file', 'search_code'],
    mode: 'review',
    match: [/\breview\b/i, /\bcritique\b.*\bcode/i, /\bfeedback on\b/i],
  }),
  S({
    id: 'dependency-analysis',
    name: 'Dependency Analysis',
    description: 'See what is installed, at what version, and what depends on it.',
    category: CATEGORY.CODING,
    icon: 'Package',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['analyze_project', 'read_file', 'run_command'],
    match: [/\bdependenc/i, /\bpackages?\b/i, /\bnpm (list|ls|outdated)\b/i],
  }),
  S({
    id: 'testing',
    name: 'Testing',
    description: 'Write and run tests, and read the output rather than assuming it passed.',
    category: CATEGORY.CODING,
    icon: 'FlaskConical',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'run_command', 'smoke_test'],
    mode: 'build',
    match: [/\btests?\b/i, /\bunit test/i, /\bcoverage\b/i, /\bvitest|jest|pytest\b/i],
  }),
  S({
    id: 'performance',
    name: 'Performance',
    description: 'Find what is slow by measuring it, then fix the cause.',
    category: CATEGORY.CODING,
    icon: 'Gauge',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command', 'browser_diagnostics', 'read_file'],
    match: [/\bperformance\b/i, /\bslow\b/i, /\boptimi[sz]e\b/i, /\bbundle size\b/i, /\bmemory leak\b/i],
  }),
  S({
    id: 'security-review',
    name: 'Security Review',
    description: 'Look for injection, exposed secrets, unsafe defaults and missing validation.',
    category: CATEGORY.SECURITY,
    icon: 'ShieldCheck',
    requires: [R.MODEL_TOOLS],
    tools: ['read_file', 'search_code'],
    mode: 'review',
    match: [/\bsecurity\b/i, /\bvulnerab/i, /\bexploit\b/i, /\bsanitis|sanitiz/i, /\binjection\b/i],
  }),
  S({
    id: 'documentation',
    name: 'Documentation',
    description: 'Write a README, API reference or guide that reflects what the code does.',
    category: CATEGORY.CODING,
    icon: 'BookOpen',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'read_file', 'generate_document'],
    match: [/\bdocument(ation)?\b/i, /\breadme\b/i, /\bwrite (the )?docs\b/i],
  }),
  S({
    id: 'frontend',
    name: 'Frontend',
    description: 'Build the interface: components, state, styling and interaction.',
    category: CATEGORY.CODING,
    icon: 'Layout',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'edit_file', 'browser_open'],
    mode: 'build',
    match: [/\bfrontend\b/i, /\breact|vue|svelte|angular\b/i, /\bcomponent\b/i, /\bcss|tailwind\b/i],
  }),
  S({
    id: 'backend',
    name: 'Backend',
    description: 'Build the server: routes, handlers, validation and persistence.',
    category: CATEGORY.CODING,
    icon: 'Server',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'edit_file', 'run_command'],
    mode: 'build',
    match: [/\bbackend\b/i, /\bserver\b/i, /\bexpress|fastify|django|flask|rails\b/i],
  }),
  S({
    id: 'full-stack',
    name: 'Full Stack',
    description: 'Build both halves and the contract between them.',
    category: CATEGORY.CODING,
    icon: 'Layers',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'edit_file', 'run_command', 'browser_open'],
    mode: 'build',
    match: [/\bfull[- ]stack\b/i, /\bend to end\b.*\bapp/i],
  }),
  S({
    id: 'database',
    name: 'Database',
    description: 'Design schemas, write migrations and get the queries right.',
    category: CATEGORY.CODING,
    icon: 'Database',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'run_command', 'read_file'],
    mode: 'build',
    match: [/\bdatabase\b/i, /\bschema\b/i, /\bmigration\b/i, /\bsql|postgres|mysql|mongo|prisma\b/i],
  }),
  S({
    id: 'api-development',
    name: 'API Development',
    description: 'Design and implement endpoints, with validation and honest error shapes.',
    category: CATEGORY.CODING,
    icon: 'Webhook',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'edit_file', 'run_command'],
    mode: 'build',
    match: [/\bapi\b/i, /\bendpoint\b/i, /\brest\b/i, /\bgraphql\b/i],
  }),
  S({
    id: 'git',
    name: 'Git',
    description: 'Inspect history and branches. Anything that discards work needs approval.',
    category: CATEGORY.CODING,
    icon: 'GitBranch',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command'],
    permission: PERMISSION.APPROVAL_REQUIRED,
    match: [/\bgit\b/i, /\bcommit\b/i, /\bbranch\b/i, /\bmerge\b/i],
  }),
  S({
    id: 'release',
    name: 'Release',
    description: 'Verify a build, package it, and produce a downloadable ZIP.',
    category: CATEGORY.CODING,
    icon: 'PackageCheck',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['smoke_test', 'run_command'],
    mode: 'build',
    match: [/\brelease\b/i, /\bpackage\b/i, /\bzip\b/i, /\bship\b/i, /\bdeliver\b/i],
  }),

  /* ---------- UI / UX ---------- */
  S({
    id: 'ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    description: 'A design reference of styles, colour palettes, font pairings and UX rules across many stacks.',
    category: CATEGORY.UI_UX,
    icon: 'Sparkles',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\bbeautiful\b/i, /\bdesign\b/i, /\bui\b/i, /\bux\b/i, /\blooks? (good|better|nice)\b/i, /\bpolish\b/i],
  }),
  S({
    id: 'design-system',
    name: 'Design System',
    description: 'Tokens, scales and component specifications that stay consistent.',
    category: CATEGORY.UI_UX,
    icon: 'Palette',
    requires: [R.GATEWAY],
    external: 'design-system',
    match: [/\bdesign system\b/i, /\btokens?\b/i, /\bconsistent\b.*\bstyl/i],
  }),
  S({
    id: 'responsive-design',
    name: 'Responsive Design',
    description: 'Make a layout work at phone, tablet and desktop, and check that it does.',
    category: CATEGORY.UI_UX,
    icon: 'Smartphone',
    requires: [R.BROWSER],
    tools: ['audit_page', 'browser_open'],
    match: [/\bresponsive\b/i, /\bmobile\b/i, /\bbreakpoint/i, /\btablet\b/i],
  }),
  S({
    id: 'accessibility',
    name: 'Accessibility',
    description: 'Contrast, keyboard access, focus order and screen-reader semantics, measured.',
    category: CATEGORY.UI_UX,
    icon: 'Accessibility',
    requires: [R.BROWSER],
    tools: ['audit_page', 'browser_inspect'],
    match: [/\ba11y\b/i, /\baccessib/i, /\bwcag\b/i, /\bscreen reader\b/i, /\bcontrast\b/i],
  }),
  S({
    id: 'ux-audit',
    name: 'UX Audit',
    description: 'Walk the real interface and report what actually gets in the way.',
    category: CATEGORY.UI_UX,
    icon: 'ClipboardCheck',
    requires: [R.BROWSER],
    tools: ['browser_open', 'browser_inspect', 'audit_page', 'browser_screenshot'],
    match: [/\bux audit\b/i, /\breview the (ui|ux|interface)/i, /\bwhat.s wrong with (this|the) (ui|design)/i],
  }),
  S({
    id: 'design-critique',
    name: 'Design Critique',
    description: 'Judge a rendered interface on hierarchy, spacing, rhythm and restraint.',
    category: CATEGORY.UI_UX,
    icon: 'Eye',
    requires: [R.BROWSER],
    tools: ['browser_screenshot', 'analyze_screenshot', 'audit_page'],
    match: [/\bcritique\b/i, /\bfeedback on\b.*\bdesign/i, /\bhow does (it|this) look\b/i],
  }),
  S({
    id: 'motion-design',
    name: 'Motion Design',
    description: 'Transitions and micro-interactions that clarify, honouring reduced-motion.',
    category: CATEGORY.UI_UX,
    icon: 'Zap',
    requires: [R.GATEWAY],
    match: [/\banimat/i, /\btransition\b/i, /\bmotion\b/i, /\bmicro[- ]interaction/i],
  }),
  S({
    id: 'component-design',
    name: 'Component Design',
    description: 'Design a component with all its states: loading, empty, error, disabled.',
    category: CATEGORY.UI_UX,
    icon: 'Component',
    requires: [R.GATEWAY],
    external: 'ui-styling',
    match: [/\bcomponent\b/i, /\bbutton|modal|dropdown|table|form\b/i],
  }),

  /* ---------- Design ---------- */
  S({
    id: 'saas-design',
    name: 'SaaS Design',
    description: 'Patterns for product UI: onboarding, billing, settings, empty states.',
    category: CATEGORY.DESIGN,
    icon: 'Building2',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\bsaas\b/i, /\bproduct (ui|app)\b/i, /\bsubscription\b/i],
  }),
  S({
    id: 'dashboard-design',
    name: 'Dashboard Design',
    description: 'Lay out metrics so the important number is the one you see first.',
    category: CATEGORY.DESIGN,
    icon: 'LayoutDashboard',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\bdashboard\b/i, /\bmetrics\b/i, /\banalytics (page|view|ui)\b/i, /\badmin panel\b/i],
  }),
  S({
    id: 'landing-page',
    name: 'Landing Page',
    description: 'Hero, proof, objection handling and one clear action.',
    category: CATEGORY.DESIGN,
    icon: 'MonitorSmartphone',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\blanding page\b/i, /\bmarketing site\b/i, /\bhero section\b/i],
  }),
  S({
    id: 'mobile-design',
    name: 'Mobile Design',
    description: 'Thumb reach, tap targets and native conventions.',
    category: CATEGORY.DESIGN,
    icon: 'Smartphone',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\bmobile app\b/i, /\bios|android\b/i, /\breact native|flutter|swiftui\b/i],
  }),
  S({
    id: 'admin-panel',
    name: 'Admin Panel',
    description: 'Dense tables, bulk actions and destructive-action safety.',
    category: CATEGORY.DESIGN,
    icon: 'Table2',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\badmin\b/i, /\bcrud\b/i, /\bback ?office\b/i],
  }),
  S({
    id: 'ai-chat-design',
    name: 'AI Chat Design',
    description: 'Streaming, citations, attachments and error states in a conversational UI.',
    category: CATEGORY.DESIGN,
    icon: 'MessageSquare',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\bchat (ui|interface|app)\b/i, /\bconversational\b/i],
  }),
  S({
    id: 'data-visualization',
    name: 'Data Visualization',
    description: 'Pick a chart that answers the question, and label it honestly.',
    category: CATEGORY.DESIGN,
    icon: 'BarChart3',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    tools: ['generate_image'],
    match: [/\bchart\b/i, /\bgraph\b/i, /\bvisuali[sz]/i, /\bplot\b/i],
  }),
  S({
    id: 'typography',
    name: 'Typography',
    description: 'Type scale, pairing and measure that stay readable.',
    category: CATEGORY.DESIGN,
    icon: 'Type',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    match: [/\btypograph/i, /\bfonts?\b/i, /\btype scale\b/i],
  }),
  S({
    id: 'color-system',
    name: 'Colour System',
    description: 'Build a palette that holds its contrast in both light and dark.',
    category: CATEGORY.DESIGN,
    icon: 'Paintbrush',
    requires: [R.GATEWAY],
    external: 'ui-ux-pro-max',
    tools: ['generate_image'],
    match: [/\bcolou?rs?\b/i, /\bpalette\b/i, /\btheme\b/i, /\bdark mode\b/i],
  }),
  S({
    id: 'icon-system',
    name: 'Icon System',
    description: 'A consistent icon set at a consistent weight and size.',
    category: CATEGORY.DESIGN,
    icon: 'Shapes',
    requires: [R.GATEWAY],
    match: [/\bicons?\b/i, /\blucide|heroicons|feather\b/i],
  }),
  S({
    id: 'design-tokens',
    name: 'Design Tokens',
    description: 'Primitive, semantic and component tokens as real CSS variables.',
    category: CATEGORY.DESIGN,
    icon: 'Binary',
    requires: [R.GATEWAY],
    external: 'design-system',
    match: [/\btokens?\b/i, /\bcss variables\b/i, /\bdesign vars\b/i],
  }),

  /* ---------- Research ---------- */
  S({
    id: 'web-search',
    name: 'Web Search',
    description: 'Search the live web across the configured providers and cite what it finds.',
    category: CATEGORY.RESEARCH,
    icon: 'Globe',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_web'],
    mode: 'research',
    settings: {
      mode: { label: 'Depth', type: 'select', options: ['fast', 'balanced', 'deep', 'free_only'], default: 'balanced' },
      maxResults: { label: 'Maximum results', type: 'number', min: 3, max: 20, default: 8 },
    },
    match: [/\bsearch\b/i, /\blatest\b/i, /\bcurrent\b/i, /\btoday\b/i, /\bnews\b/i, /\bwho is the\b/i],
  }),
  S({
    id: 'deep-research',
    name: 'Deep Research',
    description: 'Several searches, several sources read in full, cross-compared, with citations.',
    category: CATEGORY.RESEARCH,
    icon: 'Telescope',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_deep'],
    mode: 'research',
    match: [/\bdeep research\b/i, /\bresearch\b/i, /\bcompare\b.*\bsources\b/i, /\bthoroughly\b/i],
  }),
  S({
    id: 'technical-research',
    name: 'Technical Research',
    description: 'Find documentation for the version actually installed, not a stale tutorial.',
    category: CATEGORY.RESEARCH,
    icon: 'FileCode',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_web'],
    match: [/\bhow (do|to) I? ?use\b/i, /\bapi (reference|docs)\b/i, /\bdocumentation\b/i],
  }),
  S({
    id: 'github-research',
    name: 'GitHub Research',
    description: 'Search repositories, real code and issues through the official API.',
    category: CATEGORY.RESEARCH,
    icon: 'Github',
    requires: [R.SEARCH_GITHUB],
    tools: ['search_github'],
    match: [/\bgithub\b/i, /\brepo\b/i, /\bimplementation of\b/i, /\bopen source\b/i],
  }),
  S({
    id: 'news-research',
    name: 'News Research',
    description: 'Recent reporting, with publication dates distinguished from event dates.',
    category: CATEGORY.RESEARCH,
    icon: 'Newspaper',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_web'],
    match: [/\bnews\b/i, /\bbreaking\b/i, /\bwhat happened\b/i, /\brecently\b/i],
  }),
  S({
    id: 'documentation-research',
    name: 'Documentation Research',
    description: 'Go to the official docs and the changelog before anything else.',
    category: CATEGORY.RESEARCH,
    icon: 'BookMarked',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_web', 'fetch_page'],
    match: [/\bofficial docs\b/i, /\bchangelog\b/i, /\brelease notes\b/i, /\bmigration guide\b/i],
  }),
  S({
    id: 'source-verification',
    name: 'Source Verification',
    description: 'Check a claim against several independent sources and report disagreement.',
    category: CATEGORY.RESEARCH,
    icon: 'BadgeCheck',
    requires: [R.SEARCH_PROVIDER],
    tools: ['research_deep', 'fetch_page'],
    match: [/\bverify\b/i, /\bfact.?check\b/i, /\bis it true\b/i, /\bconfirm\b/i],
  }),

  /* ---------- Browser ---------- */
  S({
    id: 'browser-automation',
    name: 'Browser Automation',
    description: 'Drive a real browser: navigate, click, type, submit and read the page.',
    category: CATEGORY.BROWSER,
    icon: 'MousePointerClick',
    requires: [R.BROWSER, R.WORKSPACE],
    tools: ['browser_open', 'browser_interact', 'browser_inspect'],
    mode: 'build',
    match: [/\bclick\b/i, /\bfill (in |out )?the form\b/i, /\bnavigate\b/i, /\bin the browser\b/i],
  }),
  S({
    id: 'preview',
    name: 'Preview',
    description: 'Start the project and give you a link that actually serves it.',
    category: CATEGORY.BROWSER,
    icon: 'PlayCircle',
    requires: [R.WORKSPACE],
    tools: ['start_preview', 'stop_preview'],
    mode: 'build',
    match: [/\bpreview\b/i, /\brun (it|the app)\b/i, /\bstart the (server|app)\b/i],
  }),
  S({
    id: 'screenshot',
    name: 'Screenshot',
    description: 'Capture the rendered page at desktop, tablet or phone size.',
    category: CATEGORY.BROWSER,
    icon: 'Camera',
    requires: [R.BROWSER],
    tools: ['browser_screenshot'],
    match: [/\bscreenshot\b/i, /\bcapture\b/i, /\bshow me (what|how) it looks\b/i],
  }),
  S({
    id: 'visual-qa',
    name: 'Visual QA',
    description: 'Measure overflow, contrast, clipping, invisible text and tap targets in the real page.',
    category: CATEGORY.BROWSER,
    icon: 'ScanLine',
    requires: [R.BROWSER],
    tools: ['audit_page', 'browser_screenshot', 'analyze_screenshot'],
    mode: 'build',
    match: [/\bvisual\b/i, /\blooks? broken\b/i, /\boverflow\b/i, /\bcheck the (layout|design)/i],
  }),
  S({
    id: 'accessibility-qa',
    name: 'Accessibility QA',
    description: 'Measured contrast ratios, tap-target sizes and semantic checks on the live page.',
    category: CATEGORY.BROWSER,
    icon: 'PersonStanding',
    requires: [R.BROWSER],
    tools: ['audit_page', 'browser_inspect'],
    match: [/\baccessib/i, /\bwcag\b/i, /\bcontrast ratio\b/i],
  }),
  S({
    id: 'console-debugging',
    name: 'Console Debugging',
    description: 'Collect the JavaScript errors the page actually throws.',
    category: CATEGORY.BROWSER,
    icon: 'Terminal',
    requires: [R.BROWSER],
    tools: ['browser_diagnostics', 'browser_open'],
    mode: 'debug',
    match: [/\bconsole\b/i, /\bjs error\b/i, /\buncaught\b/i],
  }),
  S({
    id: 'network-debugging',
    name: 'Network Debugging',
    description: 'See which requests failed and with what status.',
    category: CATEGORY.BROWSER,
    icon: 'Wifi',
    requires: [R.BROWSER],
    tools: ['browser_diagnostics'],
    mode: 'debug',
    match: [/\bnetwork\b/i, /\b404\b|\b500\b/i, /\brequest fail/i, /\bcors\b/i],
  }),

  /* ---------- Files and documents ---------- */
  S({
    id: 'file-understanding',
    name: 'File Understanding',
    description: 'Read an attached file and answer questions about what is in it.',
    category: CATEGORY.FILES,
    icon: 'FileText',
    requires: [R.DOCUMENTS],
    match: [/\battach/i, /\bthis file\b/i, /\bupload/i],
  }),
  S({
    id: 'pdf',
    name: 'PDF',
    description: 'Read a PDF, answer questions about it, and edit specific regions of it.',
    category: CATEGORY.DOCUMENTS,
    icon: 'FileType',
    requires: [R.DOCUMENTS],
    match: [/\bpdf\b/i],
  }),
  S({
    id: 'docx',
    name: 'Word Documents',
    description: 'Read a .docx, and produce one with real headings, tables and styles.',
    category: CATEGORY.DOCUMENTS,
    icon: 'FileText',
    requires: [R.DOCUMENTS],
    tools: ['generate_document'],
    match: [/\bword\b/i, /\bdocx\b/i, /\bdocument\b/i],
  }),
  S({
    id: 'pptx',
    name: 'Presentations',
    description: 'Produce a real PowerPoint deck, one slide per section.',
    category: CATEGORY.DOCUMENTS,
    icon: 'Presentation',
    requires: [R.GATEWAY],
    tools: ['generate_document'],
    match: [/\bpresentation\b/i, /\bslides?\b/i, /\bpptx?\b/i, /\bdeck\b/i],
  }),
  S({
    id: 'csv',
    name: 'CSV',
    description: 'Parse a spreadsheet, respecting quoting, and reason over the rows.',
    category: CATEGORY.DATA,
    icon: 'Table',
    requires: [R.DOCUMENTS],
    match: [/\bcsv\b/i, /\bspreadsheet\b/i, /\btsv\b/i],
  }),
  S({
    id: 'json',
    name: 'JSON',
    description: 'Validate, reshape and reason over JSON.',
    category: CATEGORY.DATA,
    icon: 'Braces',
    requires: [R.DOCUMENTS],
    match: [/\bjson\b/i],
  }),
  S({
    id: 'markdown',
    name: 'Markdown',
    description: 'Read and write Markdown, and render it to PDF, Word or HTML.',
    category: CATEGORY.DOCUMENTS,
    icon: 'Hash',
    requires: [R.DOCUMENTS],
    tools: ['generate_document'],
    match: [/\bmarkdown\b/i, /\b\.md\b/i],
  }),
  S({
    id: 'code-files',
    name: 'Code Files',
    description: 'Read source in any common language with the right context.',
    category: CATEGORY.FILES,
    icon: 'FileCode2',
    requires: [R.DOCUMENTS],
    match: [/\bsource (file|code)\b/i, /\b\.(js|ts|py|go|rs|java)\b/i],
  }),
  S({
    id: 'document-qa',
    name: 'Document Q&A',
    description: 'Ask anything about an attached document and get an answer grounded in it.',
    category: CATEGORY.DOCUMENTS,
    icon: 'MessagesSquare',
    requires: [R.DOCUMENTS],
    match: [/\baccording to\b/i, /\bin the (document|pdf|file)\b/i, /\bwhat does (it|the doc) say\b/i],
  }),

  /* ---------- Image ---------- */
  S({
    id: 'deterministic-graphics',
    name: 'Deterministic Graphics',
    description:
      'Compose gradients, patterns, hero typography, social cards and charts. Not a diffusion model — it does not produce photographs.',
    category: CATEGORY.IMAGE,
    icon: 'Shapes',
    requires: [R.IMAGE_BACKEND, R.BROWSER],
    tools: ['generate_image'],
    settings: {
      format: { label: 'Format', type: 'select', options: ['png', 'svg'], default: 'png' },
    },
    match: [/\bgradient\b/i, /\bpattern\b/i, /\bog image\b/i, /\bsocial card\b/i, /\bhero (image|background)\b/i, /\bchart\b/i],
    /*
     * Never suggested for a video or a photograph. Offering a still gradient to
     * someone who asked for a video is the "substitute something adjacent"
     * failure the generation router already refuses to make.
     */
    notWhen: [/\bvideo\b/i, /\banimation\b/i, /\bclip\b/i, /\bphoto(graph|realistic)?\b/i],
  }),
  S({
    id: 'image-generation',
    name: 'Image Generation',
    description: 'Generate an image from a text description with a diffusion model.',
    category: CATEGORY.IMAGE,
    icon: 'ImagePlus',
    requires: [R.IMAGE_GENERATIVE],
    tools: ['generate_image'],
    settings: {
      backend: { label: 'Backend', type: 'select', options: ['auto', 'comfyui', 'remote'], default: 'auto' },
      resolution: { label: 'Resolution', type: 'select', options: ['512', '768', '1024'], default: '1024' },
    },
    match: [/\bgenerate (an? )?image\b/i, /\bcreate (an? )?(image|picture|photo)\b/i, /\bdraw\b/i, /\bphotorealistic\b/i],
  }),
  S({
    id: 'image-editing',
    name: 'Image Editing',
    description: 'Modify an existing image with a model.',
    category: CATEGORY.IMAGE,
    icon: 'Wand2',
    requires: [R.IMAGE_GENERATIVE],
    match: [/\bedit (this |the )?image\b/i, /\bchange the (background|colou?r)\b/i],
  }),
  S({
    id: 'image-variation',
    name: 'Image Variation',
    description: 'Produce alternatives to an image you already have.',
    category: CATEGORY.IMAGE,
    icon: 'Copy',
    requires: [R.IMAGE_GENERATIVE],
    match: [/\bvariation/i, /\balternatives?\b.*\bimage/i, /\bmore like this\b/i],
  }),
  S({
    id: 'image-to-image',
    name: 'Image-to-Image',
    description: 'Transform an image while keeping its composition.',
    category: CATEGORY.IMAGE,
    icon: 'Images',
    requires: [R.IMAGE_GENERATIVE],
    match: [/\bimg2img\b/i, /\bimage to image\b/i, /\brestyle\b/i],
  }),
  S({
    id: 'inpainting',
    name: 'Inpainting',
    description: 'Replace a masked region of an image.',
    category: CATEGORY.IMAGE,
    icon: 'Eraser',
    requires: [R.IMAGE_GENERATIVE, R.COMFYUI],
    match: [/\binpaint/i, /\bremove the\b.*\bfrom (this|the) image/i],
  }),
  S({
    id: 'outpainting',
    name: 'Outpainting',
    description: 'Extend an image beyond its original frame.',
    category: CATEGORY.IMAGE,
    icon: 'Maximize2',
    requires: [R.IMAGE_GENERATIVE, R.COMFYUI],
    match: [/\boutpaint/i, /\bextend the image\b/i, /\bwiden\b.*\bimage/i],
  }),
  S({
    id: 'upscaling',
    name: 'Upscaling',
    description: 'Increase an image resolution with a model rather than interpolation.',
    category: CATEGORY.IMAGE,
    icon: 'ZoomIn',
    requires: [R.IMAGE_GENERATIVE],
    match: [/\bupscale\b/i, /\bhigher resolution\b/i, /\benlarge\b/i],
  }),
  S({
    id: 'image-qa',
    name: 'Image QA',
    description: 'Validate a generated image: format, dimensions, and that it is not corrupt.',
    category: CATEGORY.IMAGE,
    icon: 'CheckCircle2',
    requires: [R.IMAGE_BACKEND],
  }),

  /* ---------- Video ---------- */
  S({
    id: 'text-to-video',
    name: 'Text-to-Video',
    description: 'Generate a short video from a description.',
    category: CATEGORY.VIDEO,
    icon: 'Video',
    requires: [R.VIDEO_BACKEND],
    settings: {
      duration: { label: 'Duration (s)', type: 'number', min: 2, max: 20, default: 5 },
    },
    /*
     * `\bpromo\b` never matched "promotional" — the word boundary fails against
     * the following letter — so a request for a promotional video was not
     * recognised as a video request at all.
     */
    match: [
      /\b(generate|create|make|produce)\b.{0,24}\bvideo\b/i,
      /\btext to video\b/i,
      /\b(promo\w*|advert\w*|commercial|explainer)\b.{0,16}\b(video|clip|animation)\b/i,
      /\b(video|clip)\b.{0,16}\b(promo\w*|advert\w*)\b/i,
      /\banimation\b/i,
    ],
  }),
  S({
    id: 'image-to-video',
    name: 'Image-to-Video',
    description: 'Animate a still image into a short clip.',
    category: CATEGORY.VIDEO,
    icon: 'FileVideo',
    requires: [R.VIDEO_BACKEND],
    match: [/\banimate (this|the) image\b/i, /\bimage to video\b/i],
  }),
  S({
    id: 'video-qa',
    name: 'Video QA',
    description: 'Validate container, duration, resolution and that the file actually plays.',
    category: CATEGORY.VIDEO,
    icon: 'ShieldCheck',
    requires: [R.VIDEO_BACKEND],
  }),
  S({
    id: 'video-editing',
    name: 'Video Editing',
    description: 'Trim, join and adjust an existing video.',
    category: CATEGORY.VIDEO,
    icon: 'Scissors',
    requires: [R.VIDEO_BACKEND],
    status: STATUS.COMING_SOON,
  }),
  S({
    id: 'video-extension',
    name: 'Video Extension',
    description: 'Continue a clip beyond its last frame.',
    category: CATEGORY.VIDEO,
    icon: 'FastForward',
    requires: [R.VIDEO_BACKEND],
    status: STATUS.COMING_SOON,
  }),
  S({
    id: 'storyboard-to-video',
    name: 'Storyboard-to-Video',
    description: 'Turn a shot list into a sequence of generated clips.',
    category: CATEGORY.VIDEO,
    icon: 'Clapperboard',
    requires: [R.VIDEO_BACKEND],
    status: STATUS.COMING_SOON,
  }),

  /* ---------- Audio ---------- */
  S({
    id: 'text-to-speech',
    name: 'Text-to-Speech',
    description: 'Read a reply aloud using the browser speech engine.',
    category: CATEGORY.AUDIO,
    icon: 'Volume2',
    requires: [],
    match: [/\bread (it |this )?aloud\b/i, /\bspeak\b/i, /\btext to speech\b/i],
  }),
  S({
    id: 'speech-to-text',
    name: 'Speech-to-Text',
    description: 'Dictate into the composer.',
    category: CATEGORY.AUDIO,
    icon: 'Mic',
    requires: [R.SPEECH_INPUT],
    match: [/\bdictat/i, /\bvoice input\b/i, /\bspeech to text\b/i],
  }),
  S({
    id: 'audio-analysis',
    name: 'Audio Analysis',
    description: 'Transcribe and reason about an audio file.',
    category: CATEGORY.AUDIO,
    icon: 'AudioLines',
    requires: [],
    status: STATUS.COMING_SOON,
  }),

  /* ---------- DevOps ---------- */
  S({
    id: 'build',
    name: 'Build',
    description: 'Run the project build and read what it actually says.',
    category: CATEGORY.DEVOPS,
    icon: 'Cog',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command', 'smoke_test'],
    mode: 'build',
    match: [/\bbuild\b/i, /\bcompile\b/i],
  }),
  S({
    id: 'ci-cd',
    name: 'CI/CD',
    description: 'Write and repair pipeline configuration.',
    category: CATEGORY.DEVOPS,
    icon: 'Workflow',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['write_file', 'read_file'],
    match: [/\bci\/?cd\b/i, /\bgithub actions\b/i, /\bpipeline\b/i, /\bworkflow\.ya?ml\b/i],
  }),
  S({
    id: 'deployment',
    name: 'Deployment',
    description: 'Prepare a deployment. Anything that publishes needs approval.',
    category: CATEGORY.DEVOPS,
    icon: 'Rocket',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command'],
    permission: PERMISSION.APPROVAL_REQUIRED,
    match: [/\bdeploy\b/i, /\bpublish\b/i, /\bgo live\b/i],
  }),
  S({
    id: 'environment-validation',
    name: 'Environment Validation',
    description: 'Check that required configuration is present before anything runs.',
    category: CATEGORY.DEVOPS,
    icon: 'ListChecks',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['read_file', 'run_command'],
    match: [/\benv\b/i, /\benvironment variable/i, /\bconfig(uration)? check\b/i],
  }),
  S({
    id: 'dependency-audit',
    name: 'Dependency Audit',
    description: 'Check installed packages for known advisories.',
    category: CATEGORY.DEVOPS,
    icon: 'ShieldAlert',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['run_command'],
    match: [/\baudit\b/i, /\bvulnerable (package|dependenc)/i, /\bnpm audit\b/i],
  }),
  S({
    id: 'infrastructure-review',
    name: 'Infrastructure Review',
    description: 'Read Docker, Compose and IaC files for problems.',
    category: CATEGORY.DEVOPS,
    icon: 'Container',
    requires: [R.MODEL_TOOLS],
    tools: ['read_file', 'search_code'],
    match: [/\bdocker\b/i, /\bkubernetes|k8s\b/i, /\bterraform\b/i, /\binfrastructure\b/i],
  }),

  /* ---------- Security ---------- */
  S({
    id: 'secret-scan',
    name: 'Secret Scan',
    description: 'Look for committed keys, tokens and credentials.',
    category: CATEGORY.SECURITY,
    icon: 'KeyRound',
    requires: [R.MODEL_TOOLS, R.WORKSPACE],
    tools: ['search_code', 'read_file'],
    match: [/\bsecrets?\b/i, /\bapi keys?\b/i, /\bcredential/i, /\bleaked\b/i],
  }),
  S({
    id: 'ssrf-protection',
    name: 'SSRF Protection',
    description: 'Screens every outbound fetch: scheme, address, DNS resolution and each redirect. Always on.',
    category: CATEGORY.SECURITY,
    icon: 'ShieldCheck',
    requires: [],
    mandatory: true,
    permission: PERMISSION.RESTRICTED,
  }),
  S({
    id: 'dependency-security',
    name: 'Dependency Security',
    description: 'Assess the risk a dependency actually carries.',
    category: CATEGORY.SECURITY,
    icon: 'PackageSearch',
    requires: [R.MODEL_TOOLS],
    tools: ['read_file', 'research_web'],
    match: [/\bdependency (risk|security)\b/i, /\bis .* safe to use\b/i],
  }),
  S({
    id: 'prompt-injection-review',
    name: 'Prompt Injection Review',
    description: 'Keeps retrieved and attached content fenced as data, never as instructions. Always on.',
    category: CATEGORY.SECURITY,
    icon: 'ShieldX',
    requires: [],
    mandatory: true,
    permission: PERMISSION.RESTRICTED,
  }),
  S({
    id: 'tool-security',
    name: 'Tool Security',
    description: 'Classifies every command and gates the risky ones behind approval. Always on.',
    category: CATEGORY.SECURITY,
    icon: 'Lock',
    requires: [],
    mandatory: true,
    permission: PERMISSION.RESTRICTED,
  }),

  /* ---------- Productivity ---------- */
  S({
    id: 'calculator',
    name: 'Calculator',
    description: 'Arithmetic and unit conversion, computed rather than guessed.',
    category: CATEGORY.PRODUCTIVITY,
    icon: 'Calculator',
    requires: [],
    match: [/\bcalculate\b/i, /\bhow much is\b/i, /\d+\s*[+\-*/x]\s*\d+/, /\bconvert\b.*\b(kg|lb|km|miles|celsius|fahrenheit)\b/i],
  }),
  S({
    id: 'date-time',
    name: 'Date & Time',
    description: 'Date arithmetic, time zones and durations.',
    category: CATEGORY.PRODUCTIVITY,
    icon: 'Clock',
    requires: [],
    match: [/\bwhat (day|date|time)\b/i, /\bdays? (until|since|between)\b/i, /\btime ?zone\b/i],
  }),
  S({
    id: 'formatter',
    name: 'Formatter',
    description: 'Tidy code, JSON, CSV or Markdown into a consistent shape.',
    category: CATEGORY.PRODUCTIVITY,
    icon: 'AlignJustify',
    requires: [],
    match: [/\bformat\b/i, /\bpretty ?print\b/i, /\bbeautify\b/i, /\bminif/i],
  }),
  S({
    id: 'checklist',
    name: 'Checklist',
    description: 'Turn a request with several parts into a tracked list.',
    category: CATEGORY.PRODUCTIVITY,
    icon: 'ListTodo',
    requires: [],
    match: [/\bchecklist\b/i, /\btodo\b/i, /\bstep by step\b/i, /\b\d\)\s/],
  }),
  S({
    id: 'notes',
    name: 'Notes',
    description: 'Capture and organise notes from a conversation.',
    category: CATEGORY.PRODUCTIVITY,
    icon: 'StickyNote',
    requires: [],
    match: [/\bnotes?\b/i, /\bjot down\b/i, /\bremember that\b/i],
  }),

  /* ---------- Automation ---------- */
  S({
    id: 'workflow-automation',
    name: 'Workflow Automation',
    description: 'Chain steps into a repeatable sequence.',
    category: CATEGORY.AUTOMATION,
    icon: 'Workflow',
    requires: [R.MODEL_TOOLS],
    permission: PERMISSION.APPROVAL_REQUIRED,
    match: [/\bautomate\b/i, /\bevery time\b/i, /\bworkflow\b/i],
  }),
  S({
    id: 'external-api-actions',
    name: 'External API Actions',
    description: 'Call an external API that changes state. Always requires approval.',
    category: CATEGORY.AUTOMATION,
    icon: 'Send',
    requires: [R.MODEL_TOOLS],
    permission: PERMISSION.APPROVAL_REQUIRED,
    status: STATUS.COMING_SOON,
  }),
  S({
    id: 'email',
    name: 'Email',
    description: 'Send email. Always requires approval.',
    category: CATEGORY.AUTOMATION,
    icon: 'Mail',
    requires: [],
    permission: PERMISSION.APPROVAL_REQUIRED,
    status: STATUS.COMING_SOON,
  }),
  S({
    id: 'calendar',
    name: 'Calendar',
    description: 'Read and create calendar events. Creating requires approval.',
    category: CATEGORY.AUTOMATION,
    icon: 'CalendarDays',
    requires: [],
    permission: PERMISSION.APPROVAL_REQUIRED,
    status: STATUS.COMING_SOON,
  }),
]

/** Skills that are always on and cannot be switched off. */
export const MANDATORY = BUILT_IN.filter((s) => s.mandatory).map((s) => s.id)

export { S }
